export const SCORE_THRESHOLDS = {
  EXCELLENT: 90,
  GOOD: 70,
  POOR: 50
};

export const AUDIT_WEIGHTS = {
  TECHNICAL: 0.3,
  ONPAGE: 0.3,
  OFFPAGE: 0.2,
  ANALYTICS: 0.1,
  ADVANCED: 0.1
};

export const MAX_POLL_ATTEMPTS = 30;
export const POLL_INTERVAL = 2000;
export const HEALTH_CHECK_INTERVAL = 300000;